name: Run PHP Script and Update Keys

# Trigger the workflow on a schedule (daily at midnight UTC) and allow manual triggers
on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:       # Allows manual triggering of the workflow

jobs:
  update-keys:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Disable automatic token injection

      # 2. Set Up Git User and Email
      - name: Set Up Git User
        uses: fregante/setup-git-user@v2
        with:
          name: github-actions[bot]
          email: github-actions[bot]@users.noreply.github.com

      # 3. Set Up PHP Environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'          # Specify the PHP version you need
          extensions: mbstring, curl  # Add any required PHP extensions
          ini-values: post_max_size=256M, upload_max_filesize=256M

      # 4. Install Composer Dependencies (Optional)
      - name: Install Composer Dependencies
        if: file_exists('composer.json')
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          composer install --no-progress --no-suggest --prefer-dist

      # 5. List Repository Files (Diagnostic Step)
      - name: List Repository Files
        run: |
          echo "Listing repository root:"
          ls -la
          echo "Listing 'scripts/' directory:"
          ls -la scripts/

      # 6. Run PHP Script
      - name: Run PHP Script
        run: php scripts/fetch_keys.php

      # 7. List 'plus/' Directory Contents for Verification
      - name: List 'plus/' Directory
        run: ls -la plus/

      # 8. Display Contents of 'full' and 'lite' Files (Optional)
      - name: Display 'full' File Contents
        run: cat plus/full || echo "'full' file does not exist."

      - name: Display 'lite' File Contents
        run: cat plus/lite || echo "'lite' file does not exist."

      # 9. Commit Changes if Any
      - name: Commit Changes
        run: |
          # Check for changes in the 'plus' directory
          if git diff --quiet plus; then
            echo "No changes detected in 'plus' directory."
          else
            git add plus/full plus/lite
            git commit --message "Update keys on $(date +'%Y-%m-%d')"
          fi

      # 10. Push Changes
      - name: Push Changes
        if: github.ref == 'refs/heads/main'  # Replace 'main' with your default branch if different
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Only push if there are commits to push
          if git rev-parse --verify HEAD >/dev/null 2>&1; then
            git push origin HEAD:${{ github.ref }}
          else
            echo "No commits to push."
          fi
