name: "Collect Keys"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs at minute 0 of every hour

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0}
    steps:
      # 1. Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # 2. Setup PHP Environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'              # Updated PHP version for better features and security
          extensions: mbstring, curl      # Added required PHP extensions
          ini-values: post_max_size=256M, upload_max_filesize=256M  # Increased limits if needed

      # 3. Execute PHP Script
      - name: Execute PHP script
        run: php scripts/fetch_keys.php

      # 4. Set Up Git User and Email
      - name: Set Up Git User
        uses: fregante/setup-git-user@v2
        with:
          name: ''
          email: ''

      # 5. Commit Changes if Any
      - name: Commit changes
        run: |
          # Stage all changes in the 'plus/' directory
          git add plus/full plus/lite

          # Check if there are any staged changes
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            # Commit with a timestamped message in Tehran timezone
            git commit -m "💡 Automatic update - $(TZ='Europe/Warsaw' date '+%Y-%m-%d %H:%M')"
          fi

      # 6. Push Changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
